### ISSUE TITLE
Ventura on u729 is a winner (thx :) ) - but booting Sonoma gives a flashing screen

### ISSUE THREAD

**Issue by ghost** [KrzysiuWojcik/Fujitsu-Lifebook-U748-Hackintosh#3]
Hi,

First of all - thank you for making this great effort in making it work. I don't have the 748 but i have the smaller sibling the 729 and after a few days of reading Dortiana & your plist, i managed to install Ventura which works rather great actually :)

Then i wanted to try Sonoma and so i made the installer USB, copied the OC efi over to the EFI partition and made the changes suggested (platform-id change) and i noticed the same behaviour as i did initially with Ventura:

It reaches the first part of the installer (install, restore, etc) but it just keeps flashing (3 second of black screen, 0.2 second of backlight, in a repated cycle). Any hints about how to circumvent/remedy this?

**Comment by KrzysiuWojcik** [comment]
Hello, thank you for your message. I stopped working on this OC as I no
longer have this laptop, I moved to MacBook Air. But I think that it may be
either platform-id, SMBIOS, or both of them. There were a couple of
combinations that worked for me. I have chosen my config on Big Sur where
my screen was recognized as retina one and I could change my DPI. On
Monterey and Ventura it no longer worked but screen itself was working so I
was not touching that. On Sonoma I had to change my config, but I have
chosen the first one that worked and never really tested it as shortly
after it I moved to real MacBook.
If I were you, I would make a dual boot for Ventura and Sonoma, then on
Ventura I would install Hackintool and set some platform-id and SMBIOS and
try to boot Sonoma, and after it fails, again, Ventura, Hackintool &
reboot. I have no idea for something better 😕
You can change configs on OC installed on USB stick, so you won’t lose your
Ventura setup.
I wish you the best of luck!

W dniu śr., 23 paź 2024 o 20:20 my05 ***@***.***> napisał(a):

**Comment by ghost** [comment]
Thank you Kryszek,

and as a matter of fact, i could successfully install Sonoma this evening with great help from your guide :)

What i needed to do was basically:

- append the boot-arg string with:-igfxblt -no_compat_check

To overcome any unsupported SMBIOS and the platform-id setting that i used for the UHD 620.


My ig-platform-id is:09009B3E 
and my devide-id is:9B3E0000   (but i think this is mostly ignored anyway)

And of course, after install, like in your guide, replace AirportWlm with Itwlm and Heliport.

Bluetooth can still find mice, etc but not connect and so this is the next challenge before trying the ultimate seqouia :)

Huge thank you.

br

Dan

**Comment by ghost** [comment]
Hi, for a few weeks now i have been running Sequioa on the 729 (and i'm quite sure it works on the 74x and 75x as well) using basically the exact same config as for Sonoma :)

Everything works extremely smooth except for BT so far (i'm investigating why that is) so its all great. Just a heads up as you where the one putting the foundation in place, making it all possible

**Comment by temporal-distortion** [comment]
After some tinkering, i have it running on Sequioa if anyone else wants to try it out and bring it forward:

https://github.com/temporal-distortion/Fujitsu_Sequioa_hackintosh_u729_u748_u758

Of course, needless to say, this is courtesy of KrzysiuWojcik who did the essential ground work :)
